CREATE TABLE IF NOT EXISTS posts (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uuid CHAR(36) UNIQUE,
	tag_uuid CHAR(36) NOT NULL,
	user_uuid CHAR(36) NOT NULL,
	title VARCHAR(255) NOT NULL,
	thumbnail TEXT,
	content TEXT NOT NULL,
	slug TEXT NOT NULL,
	keyword TEXT NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT true,
	is_highlight BOOLEAN NOT NULL DEFAULT false,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
);
